import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './components/organisms/Navbar';
import '../styles/globals.css';
import Footer from './components/organisms/Footer';
import { AuthProvider } from '@/context/AuthContext'; // Verifique o caminho de importação

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Black Square',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/BS-favicon.png" />
      </head>
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <AuthProvider> {/* Adicione o AuthProvider aqui */}
          <header className="bg-white shadow p-4">
            <Navbar />
          </header>
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
