// src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './app/components/organisms/Navbar';
import './styles/globals.css';
import Footer from './app/components/organisms/Footer';
import { AuthProvider } from './context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Black Square',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
return (
      <html lang="en">
        <head>
          <link rel="icon" href="/BS-favicon.png" />
        </head>
        <body className={`${inter.className} flex flex-col min-h-screen`}>
          <header className="bg-white shadow p-4">
            <Navbar />
          </header>
          <main className="flex-grow">
            <AuthProvider>
              {children}
            </AuthProvider>
          </main>
          <Footer />
        </body>
      </html>
    );
}
